name: test-files

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  merge_group:

jobs:
  test-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          extra-packages: |
            any::gh
            any::testthat
            any::here
            any::purrr
          needs: check

      - name: Run tests
        run: | 
          testthat::test_dir("tests")
        shell: Rscript {0}